---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1qrcp9tere48q47tcywmfgumd99uwt5gcmrjgtz43a27jt3asl3mshn2xg5"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1qrcp9tere48q47tcywmfgumd99uwt5gcmrjgtz43a27jt3asl3mshn2xg5"
