apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nW8tbM68/U51tIdWbz/jHF/sosCXoYHeIZEOLZ+YdhoMQ/yd,iv:GJ0UY64pt+RS3Bg+3E5HN1iN8UOSSfjC43vlkxdZOn0=,tag:+WZ1mPPpqT73x9lfFZqE/w==,type:str]
    credentials.json: ENC[AES256_GCM,data:5NGEhy8gH8o6ANGHiMnL8kbX3Z6k52kjQwMPlkWZnRQBM60BLsQjW9ytwO93cGe7hcPMPa4EIu0ujxVPYCJEYYs3MAbxuYr030TsdkSjt0aSrgNL/FvV7NTcCAPYWa7/Pb8Zt8QfrByCKHv+lzdeLiXNP4BzGYJfL/6rzGdN2ynmJiXtey4aoctWDMXJCGb+p186aIhEF71fva44blqKXMnwrY8wPI3tP3tibXQLSg==,iv:Kao52T26Ozdad/M0Ls4udeh9XreG4TwGFUfZa3XdJ54=,tag:PB4wwOnuFHiU0q/dVslagw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qrcp9tere48q47tcywmfgumd99uwt5gcmrjgtz43a27jt3asl3mshn2xg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NnFTb1ZodDRmcHhoWHRx
            MldCOXdZNHoxdVhob0Foa3NGSzhDUG9US3pVCnprVkVaZkFlYmZOb3VYR05kWk9p
            U0dwcDd5cnE0TS8wOUd2eGJYc3gxL2MKLS0tIDN1eDFmSnk1cEZ1bTA3OWN2L2ox
            dWFoanE5ZW5wb2pMSnZMWldsUGVFMTQKh7mC9g3LLo0O7nHl3hYWElXhb9yvApdy
            uCRaUKzQzhkaWnuI+qalY5AAMWtsiYUu/om1ZXw1GgmITYxdkV2yFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T01:16:51Z"
    mac: ENC[AES256_GCM,data:mhM7XsorKXKDqPLxGFAivBa+X2A8n7Ci3djShfu1ayjuEzD9eN9dkfF5haIhArSjVcm62saZQW0KaWuJOLxdTMj4WdplU4Njf1pbKbvtgT+8P6Ug4VYL/KaJXbZn+LDuDGgNgxzsY7Nn+fq2dvZ/wuovw0EwRgfLMBGZw0NP2bo=,iv:DKXYqsOjq++Xa5cU6CvvZkJyiVb81FyxqRxqqyKtJIs=,tag:IGMHBzYQFrtA66XAnszBjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
