apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SwIXlvTIu/ifgU8mAzc4de653A==,iv:VY/jImj8GUM5Npjk7GVPJNIGrFF2OcdZqC5lHspTNcU=,tag:1m51IvVqMR97U+zrFxJQBQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:UJnHVlWuPaBA6grQRErZJpHVyvsC0e8RNQ==,iv:GvSw4N/l8RnSLFQfFr2IOcgbsYQTY85jwAc+tjgKvP0=,tag:skZA1nBDg9FtrvLUr7zs/g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3lAwYGqianNrl4kyHVLfHvHMQ1syBAm+C2NJdS7XDbNV/3Sn,iv:a5zed2DwNBxJSQHM6PKShpKwv7TEfmKnZgLAJKNjTMc=,tag:e37uTi/lZeXGCSVgxoYn2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qrcp9tere48q47tcywmfgumd99uwt5gcmrjgtz43a27jt3asl3mshn2xg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjc1UFpzclV1Tk9BMlEr
            bTYrMkl6dkFBNkZTeVFlZWt1dFRTMGFRMnhnCmQxVGV0andnVDRMYnA3Z2pHbjJJ
            bzd3MVFpdWVBTmdpN0NQZ0E5KzJGbDQKLS0tIHc3MFJCQ1BZWXNQdlA5VnM0UWpt
            QjRmdWg1MEJxVEQrOHpTR21kemQzYk0KtPrh6k9mZmHTpMdsfSaw9rFPy4hb1WL9
            TG92ikp11pWThfzHFG0QF5AadKSJgH/awf/CvbJJpTM358igtVVSAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T03:12:55Z"
    mac: ENC[AES256_GCM,data:lHPs4Lx9BHglDGRGDDG/ClVGNtt8TwsE8UZ3ycgfFEN4W8kQpylrxtLlFzbbzdj2d+koNobYJOQBC1QBv4WuGVUl1Qit5nW/aa0IV+qGXLK6OZbHNqso4CorT4G1Bid8CMjrRsI/VdjroBAm/RhIfPj5yoatMIetTk1Emc/xO+0=,iv:q+7LGw/3+/8YgBHAoYUn7XX3vr20+J7OBuNY6fv/jNw=,tag:FaeOPveK3U4Dov6bEVhd/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
