apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VemPkDiRZTq8t6M6IsxCqigTEVn8/bigXeXKQMQ/sDBDTXXyOw4fSA==,iv:o9qFrDtwud3JRn1zcSxCH9krr4Q6PAxvm76wD+HnZdk=,tag:tDzRgTjp8gretKhFOyxUzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qrcp9tere48q47tcywmfgumd99uwt5gcmrjgtz43a27jt3asl3mshn2xg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZTB6cW9QVytPclBzR01G
            ckluZXRJTXI2K0ZDazU5RG80UGU4L3NmY2djCkMwQXNaKzlROGR1YzB0ZlZKdXdG
            N1dqQmRmbUVWd1lnWk9odERsYXQ5RG8KLS0tIHBBYWNtVjNjd1l2K0wyN1dnbyts
            ZGs2dmE2a3lJRGF6YUkxbHJacHprMU0KyH4eWOHwPFO6Gar7xPNLqQXzRzqgz6vp
            7Yy/+zxWzpjlvRBk20Q2gw2Nl6dezGiIXGPoqqbWbOTvc9PJk0kt/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T01:16:51Z"
    mac: ENC[AES256_GCM,data:uuliRgF2ex7OtD75DPOrRy3tgyyPkUjIUaoasi8HsWrhnpT6dNnG0RSA4FsNu3mFXwFKObDUL5jfD20sBHB9DDR8bcRbN2C/f0qcLikX5TLo7fK38eHQmSyMV0XL9G34aZVJRVLR377DYkSwq6Izad8Ui+g4k04OikxcVyKLlJc=,iv:cw+f/PnDI9U7S5mUP+jfFIBqPu3I7sgyou0FnX1tmNE=,tag:t84ITWLrVRmRjltrJnK1JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
